name: PR Linter

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  run-linter:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.4.1'

      - name: Install dependencies
        run: npm install

      - name: Run linter
        run: npx eslint . --ext .ts
